### ISSUE TITLE
Registrierung implementieren

### ISSUE THREAD

**Issue by easylite376** [easylite376/PIN.UP#23]
Es sollte die Registierung implementiert werden mit einer vorherigen Validierung über das Moodle der Universität.

TO-DO:
 - Validierungsformular erstellen
 - Validierung implementieren
 - Registrierungformular erstellen
 - Registierung implementieren (inkl. Speicherung in Datenbank)
 - Username Überprüfung (schon vorhanden)

**Comment by klopskerl** [comment]
regex email,daten aus json ziehen

**Comment by mirueger** [comment]
Texte auf deutsch (hard reinschreiben reicht)
