### ISSUE TITLE
data DAO erstellen

### ISSUE THREAD

**Issue by klopskerl** [easylite376/PIN.UP#30]

**Comment by mirueger** [comment]
//bestimmte Anzahl an Posts für aktuelle Seite anzeigen (evtl. nach anderen Funktionen aufrufen? zb nach Suche)
getPosts(int postsPerPage, int page, List<Data> data)

//alle Posts eines Users anzeigen (oder eigene)
getPostsByUser(long userID)

//alle Posts für bestimmtes Datum bzw Zeitraum (erstelldatum?)
getPostsByDate(Date date)
getPostsByDate(Date start, Date end)

usw.

**Comment by easylite376** [comment]
alles implementiert 👍
